# Generated by Django 5.2 on 2025-05-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodanalyzer',
            options={'verbose_name': 'Blood Analyzer', 'verbose_name_plural': 'Blood Analyzers'},
        ),
        migrations.AddField(
            model_name='bloodanalyzer',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Source system where this device is registered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.datasource'),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='assigned_technician',
            field=models.ForeignKey(help_text='Technician responsible for this device', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='device_id',
            field=models.CharField(help_text='Unique device identifier (e.g., VA-205-0001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='device_type',
            field=models.CharField(choices=[('production', 'Production Model'), ('prototype', 'Prototype'), ('research', 'Research Unit')], default='production', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='last_calibration',
            field=models.DateTimeField(help_text='Last calibration date and time'),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='location',
            field=models.CharField(help_text='Current location of the device', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='manufacturing_date',
            field=models.DateField(help_text='Date when the device was manufactured'),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='next_calibration_due',
            field=models.DateTimeField(editable=False, help_text='Next calibration due date'),
        ),
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bloodanalyzer',
            index=models.Index(fields=['data_source'], name='devices_blo_data_so_7949e5_idx'),
        ),
    ]
