# Generated by Django 5.2 on 2025-05-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_token_auth'),
        ('devices', '0003_create_factory_tables'),
    ]

    operations = [
    ]
