# Generated by Django 5.2 on 2025-05-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_merge_0003_add_token_auth_0003_create_factory_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Test Run', 'verbose_name_plural': 'Test Runs'},
        ),
    ]
