# Generated by Django 5.2 on 2025-05-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_datasource_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodanalyzer',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Source system where this device is registered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.datasource'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='devices.datasource'),
        ),
    ]
